import { createAdminClient } from '@/lib/supabase-server'
import { updateProposalJobProgress } from '@/lib/proposal-job-events'
import { SolarUtils } from '@/lib/solar-utils'
import type { Prospect } from '@/lib/prospect'
import type {
  SolarDataLayerAsset,
  SolarGeoBounds,
  SolarModel,
  SolarRoofFocusCrop,
  SolarRasterPlacement,
  VisualReferenceSet,
} from '@/lib/openclaw-google'

export const DEFAULT_SITE_URL = 'https://heliocap.vercel.app'
export const PROPOSAL_RENDER_WIDTH = 1280
export const PROPOSAL_RENDER_HEIGHT = 720
export const PROPOSAL_RENDER_WIDE = { width: 1600, height: 1000 }
export const PROPOSAL_RENDER_SQUARE = { width: 1400, height: 1400 }
export const PROPOSAL_RENDER_TALL = { width: 1200, height: 1600 }

export type AdminSupabase = Awaited<ReturnType<typeof createAdminClient>>

export type WorkflowJob = {
  id: string
  business_name: string
  address: string
  lat: number
  lng: number
  slug: string
  proposal_url?: string | null
  receipt: Record<string, unknown> | null
}

export type ProspectLookup = Pick<
  Prospect,
  | 'id'
  | 'address'
  | 'business_name'
  | 'owner_name'
  | 'owner_llc'
  | 'first_name'
  | 'last_name'
  | 'homeowner_email'
  | 'homeowner_phone'
  | 'owner_email'
  | 'owner_phone'
  | 'sqft'
  | 'annual_savings'
  | 'payback_years'
  | 'use_code'
> & {
  visual_reference_exclusions?: string[] | null
  solar_reference_enabled?: boolean | null
  solar_reference_url?: string | null
}

export type UsableSolarRgbLayer = SolarDataLayerAsset & {
  sourceUrl: string
  sourceWidth: number
  sourceHeight: number
  previewUrl: string
  bounds: SolarGeoBounds
  previewWidth: number
  previewHeight: number
}

export type ProposalRenderSize = {
  width: number
  height: number
  aspect: 'wide' | 'square' | 'tall'
}

export type RoofAssets = {
  roofImageUrl: string
  roofImageSourceUrl: string
  maskImageUrl: string | null
  renderImageUrl: string
  renderPreviewUrl: string
  panelLayerSvg: string
  focusCrop: SolarRoofFocusCrop | null
  renderSize: ProposalRenderSize
  presentationRotationDegrees: number
  solarDataLayers: SolarDataLayerAsset[]
  solarRgbLayer: UsableSolarRgbLayer
  visualReferences: VisualReferenceSet
  solarModel: SolarModel
  mapCenter: { lat: number; lng: number }
}

export async function setWorkflowProgress(
  supabase: AdminSupabase,
  job: WorkflowJob,
  {
    status = 'running',
    step,
    progressPercent,
    buildStatus,
    receipt,
    errorMessage,
  }: {
    status?: 'queued' | 'running' | 'completed' | 'failed'
    step: string
    progressPercent: number
    buildStatus?: string
    receipt?: Record<string, unknown>
    errorMessage?: string
  },
) {
  const mergedReceipt = {
    ...asRecord(job.receipt),
    ...(receipt || {}),
    ...(buildStatus ? {
      build_status: buildStatus,
      build_status_label: getBuildStatusLabel(buildStatus),
    } : {}),
    engine: 'app',
    updated_at: new Date().toISOString(),
  }
  job.receipt = mergedReceipt

  await updateProposalJobProgress(supabase, {
    jobId: job.id,
    businessName: job.business_name,
    status,
    step,
    progressPercent,
    errorMessage,
    receipt: mergedReceipt,
  })
}

export function getContactName(prospect: ProspectLookup | null) {
  if (!prospect) return null
  const homeownerName = [prospect.first_name, prospect.last_name].filter(Boolean).join(' ').trim()
  return homeownerName || prospect.owner_name || prospect.owner_llc || null
}

export function buildLeadNotes(prospect: ProspectLookup | null, renderSource: string) {
  const parts = [
    'Generated by the in-app proposal workflow.',
    `Render source: ${renderSource}.`,
    prospect?.homeowner_email ? `Homeowner email: ${prospect.homeowner_email}.` : null,
    prospect?.homeowner_phone ? `Homeowner phone: ${prospect.homeowner_phone}.` : null,
    prospect?.owner_email ? `Owner email: ${prospect.owner_email}.` : null,
    prospect?.owner_phone ? `Owner phone: ${prospect.owner_phone}.` : null,
  ]

  return parts.filter(Boolean).join(' ')
}

export function getBuildStatusLabel(status: string) {
  return status
    .split('_')
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ')
}

export function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === 'object' && !Array.isArray(value)
    ? value as Record<string, unknown>
    : {}
}

export function getString(value: unknown) {
  return typeof value === 'string' && value.trim() ? value.trim() : undefined
}

export function getStringArray(value: unknown) {
  if (!Array.isArray(value)) return []
  return value.filter((entry): entry is string => typeof entry === 'string' && entry.startsWith('http'))
}

export function getUsableSolarRgbLayer(layers: SolarDataLayerAsset[]): UsableSolarRgbLayer | null {
  const rgbLayer = layers.find((layer) => layer.id === 'rgb')
  const sourceUrl = rgbLayer?.originalUrl || rgbLayer?.previewUrl
  const sourceWidth = rgbLayer?.originalUrl && rgbLayer.width ? rgbLayer.width : rgbLayer?.previewWidth
  const sourceHeight = rgbLayer?.originalUrl && rgbLayer.height ? rgbLayer.height : rgbLayer?.previewHeight
  if (
    !sourceUrl ||
    !sourceWidth ||
    !sourceHeight ||
    !rgbLayer?.previewUrl ||
    !rgbLayer.bounds ||
    !rgbLayer.previewWidth ||
    !rgbLayer.previewHeight
  ) {
    return null
  }

  return {
    ...rgbLayer,
    sourceUrl,
    sourceWidth,
    sourceHeight,
    previewUrl: rgbLayer.previewUrl,
    bounds: rgbLayer.bounds,
    previewWidth: rgbLayer.previewWidth,
    previewHeight: rgbLayer.previewHeight,
  }
}

export function selectProposalRenderSize(
  focusCrop: SolarRoofFocusCrop | null,
  layer: Pick<UsableSolarRgbLayer, 'sourceWidth' | 'sourceHeight'>,
): ProposalRenderSize {
  const width = focusCrop?.width || layer.sourceWidth
  const height = focusCrop?.height || layer.sourceHeight
  const aspect = width / Math.max(height, 1)

  if (aspect >= 1.4) return { ...PROPOSAL_RENDER_WIDE, aspect: 'wide' }
  if (aspect <= 0.7) return { ...PROPOSAL_RENDER_TALL, aspect: 'tall' }
  return { ...PROPOSAL_RENDER_SQUARE, aspect: 'square' }
}

export function buildRenderQualityFlags({
  panelCount,
  focusCrop,
  layer,
  rotationDegrees,
  hasMask,
}: {
  panelCount: number
  focusCrop: SolarRoofFocusCrop | null
  layer: Pick<UsableSolarRgbLayer, 'sourceWidth' | 'sourceHeight'>
  rotationDegrees: number
  hasMask: boolean
}) {
  const flags: string[] = []
  if (panelCount < 6 || panelCount > 800) flags.push('panel_count_sanity')
  if (!hasMask) flags.push('mask_unavailable')
  if (Math.abs(rotationDegrees) > 15) flags.push('rotation_magnitude')

  if (focusCrop) {
    const sourceArea = Math.max(1, layer.sourceWidth * layer.sourceHeight)
    const cropCoverage = (focusCrop.width * focusCrop.height) / sourceArea
    if (cropCoverage < 0.08) flags.push('roof_coverage_too_small')
    if (cropCoverage > 0.85) flags.push('roof_coverage_too_large')
  } else {
    flags.push('roof_focus_missing')
  }

  return flags
}

export function getSolarRgbRasterPlacement(
  layer: UsableSolarRgbLayer,
  renderSize: Pick<ProposalRenderSize, 'width' | 'height'> = {
    width: PROPOSAL_RENDER_WIDTH,
    height: PROPOSAL_RENDER_HEIGHT,
  },
  focusCrop?: SolarRoofFocusCrop | null,
): SolarRasterPlacement {
  const cropWidth = focusCrop?.width || layer.sourceWidth
  const cropHeight = focusCrop?.height || layer.sourceHeight
  const scale = Math.min(
    renderSize.width / cropWidth,
    renderSize.height / cropHeight,
  )
  const renderedWidth = Math.round(cropWidth * scale)
  const renderedHeight = Math.round(cropHeight * scale)

  return {
    bounds: layer.bounds,
    sourceWidth: layer.sourceWidth,
    sourceHeight: layer.sourceHeight,
    sourceLeft: focusCrop?.left || 0,
    sourceTop: focusCrop?.top || 0,
    cropWidth,
    cropHeight,
    renderedWidth,
    renderedHeight,
    left: Math.round((renderSize.width - renderedWidth) / 2),
    top: Math.round((renderSize.height - renderedHeight) / 2),
  }
}

export function getPresentationRotationDegrees(
  solarLayoutDebug: {
    selectedSegments: Array<{ azimuthDegrees?: number | null }>
  },
) {
  const primarySegment = solarLayoutDebug.selectedSegments[0]
  if (typeof primarySegment?.azimuthDegrees !== 'number') return 0

  const roofAxis = normalizeDegrees(primarySegment.azimuthDegrees - 90)
  const nearestRightAngle = Math.round(roofAxis / 90) * 90
  let rotation = nearestRightAngle - roofAxis

  if (rotation > 45) rotation -= 90
  if (rotation < -45) rotation += 90
  if (Math.abs(rotation) < 4) return 0

  return Number(rotation.toFixed(2))
}

export function describeUnknownError(error: unknown) {
  if (error instanceof Error) {
    return {
      message: error.message,
      name: error.name,
      stack: trimStack(error.stack),
      cause: describeCause(error.cause),
    }
  }

  if (error && typeof error === 'object') {
    const record = error as Record<string, unknown>
    const message = getString(record.message) ||
      getString(record.error_description) ||
      getString(record.error) ||
      safeJson(error)

    return {
      message,
      name: getString(record.name),
      code: getString(record.code),
      status: typeof record.status === 'number' ? record.status : undefined,
      statusText: getString(record.statusText),
      details: getString(record.details),
      hint: getString(record.hint),
      raw: safeJson(error),
    }
  }

  return {
    message: typeof error === 'string' && error.trim()
      ? error
      : 'Unknown proposal workflow error',
    raw: String(error),
  }
}

export async function getUniqueLeadSlug(baseValue: string) {
  const supabase = await createAdminClient()
  const baseSlug = SolarUtils.generateSlug(baseValue)
  let slug = baseSlug

  for (let attempt = 1; attempt <= 8; attempt += 1) {
    const { data, error } = await supabase
      .from('leads')
      .select('id')
      .eq('slug', slug)
      .maybeSingle()

    if (error) throw error
    if (!data) return slug
    slug = `${baseSlug}-${attempt + 1}`
  }

  return `${baseSlug}-${Date.now().toString(36)}`
}

function normalizeDegrees(value: number) {
  return ((value % 360) + 360) % 360
}

function describeCause(cause: unknown) {
  if (!cause) return undefined
  if (cause instanceof Error) {
    return {
      message: cause.message,
      name: cause.name,
      stack: trimStack(cause.stack),
    }
  }
  return safeJson(cause)
}

function safeJson(value: unknown) {
  try {
    return JSON.stringify(value)
  } catch {
    return String(value)
  }
}

function trimStack(stack: string | undefined) {
  if (!stack) return undefined
  return stack.split('\n').slice(0, 8).join('\n')
}
